- b4_drf_project/settings.py
- exhibitions/views.py
페이지네이션 설정 추가
페이지네이션 기본 구현 완료
[필요]
전체 조회 전용 serializer 정의
> :sparkles:Feat: 전시회 전체 조회 페이지네이션 #26

- exhibitions/views.py
구현한 정렬 기능과 별개로 프론트에서 효율적으로
카테고리를 보여주기 위해서 ManyToMnay로 변경해야 할지
고민 필요
> :sparkles:Feat: 카테고리 별 정렬 기능 구현 #27

- users/admin.py
- users/models.py
- users/views.py
[수정 및 삭제]
1. users/views.py 에서 의미없는 코드  print(serializer.error) 삭제
2. users/views.py 에서 class UserDetailView 안의 def get 함수 삭제 **회원정보 조회는 추후 마이페이지파트에서 따로 구현할 예정
3. users/views.py 에서 class UserDetailView 안의 patch 함수 내 user 선언하는 방식을 user = request.user로 수정
4. users/models.py 에서 def__str__(self): 함수내의 리턴값을 return self.nickname 으로 수정
[추가]
1. users/admin.py 에서 유저관리용 기본 CRUD 코드 추가
2. users/models.py 에서 유저데이터에 자기소개를 위한 bio 필드 생성 ** erd에 textfield로 데이터타입 수정이 필요합니다. 임시로 char 로 되어있는듯 합니다.
> :hammer:Refact:회원기능 관련 자잘한 코드 보완

- reviews/serializers.py
ReviewCreateSerializer 필드에 user 제거
> :hammer:Refact: 시리얼라이저 불필요한 코드 제거

- reviews/models.py
> :hammer:Refact: 리뷰 모델 필드 수정

- users/models.py
- users/urls.py
urls.py 의 url name들이 케밥케이스로 정리되었습니다.
사용자 프로필 이미지가 저장되는 profile-images 폴더명이 profile_images로 변경되었습니다.
> :art:Style:회원기능 코드리뷰 후 작은 수정

- reviews/models.py
user, exhibition related_name 추가
> :hammer:Refact: 리뷰 모델 ForeignKey related_name 추가

- exhibitions/paginations.py
- exhibitions/serializers.py
- exhibitions/views.py
views.py 누락된request 추가
related_name 추가 반영
OrderedDict 사용
> :bug:Fix:누락된 변경사항 추가 close #12

- exhibitions/urls.py
- exhibitions/views.py
전시회 제목& 내용
리뷰 내용
동행 구하기 내용으로 검색 가능
> :sparkles:Feat:전체 검색기능 구현 close #28

- exhibitions/views.py
> :sparkles:Feat: 검색결과 페이지네이션 적용 #28

- exhibitions/tests.py
전시회CRUD 조회, 작성, 수정, 삭제, 좋아요, 이미지 테스트 코드 작성
> :umbrella:Test: 전시회(게시글) 테스트 코드 작성

- exhibitions/serializers.py
- exhibitions/views.py
전시회 정보를 불러오고 좋아요 갯수를 반영하기 위한 데이터 return 추가
> :sparkles:Feat: 프론트용 like 반영 데이터 추가 #16

- exhibitions/recommend_ml.py
start_date가 오늘이거나 오늘 이후이고, end_date가
오늘이거나 오늘 이후인 전시회만 뽑아서 추천됩니다.
> :sparkles:Feat: 날짜 필터링 된 추천 기능 #74

- exhibitions/views.py
메인페이지에 보이는 전시회의 경우 현재 날짜를 기준으로 전시 종료가 되지
않은 전시회만 보여주는 기능을 추가했습니다.
> :sparkles:Feat: 전시회 목록 조회 시 날짜 필터링 추가 #26

- users/serializers.py
유저가 좋아요를 누른 전시회 데이터를 담고 있는 exhibition_likes 필드 추가했습니다.
> :sparkles:Feat: 마이페이지에 유저가 좋아한 전시회 목록 필드 추가 #26

- users/serializers.py
Reverts sdoram/b4_exhibitions_backend#82
> Revert ":sparkles:Feat: 마이페이지에 유저가 좋아한 전시회 목록 필드 추가 #26"

- users/serializers.py
유저가 좋아요를 누른 전시회 데이터를 담고 있는 exhibition_likes 필드
추가했습니다.
> :sparkles:Feat: 마이페이지에 유저가 좋아한 전시회 목록 필드 추가 #11

- exhibitions/recommend_ml.py
유사도 측정 시 카테고리와 장소를 고려해 보려고 하였으나 오히려 추천되는 전시회가 다양하지 않은 결과가 나와서 그냥 필요 없는 부분만 삭제해서 PR 보냅니다..
> :art:Style: 프린트문 삭제 close #74

- exhibitions/serializers.py
- users/serializers.py
가져온 id를 통해서 serializer를 거쳐 likes count 정보 전달
> :hammer:Refact: 마이페이지 정보 수정 close #11

- users/serializers.py
회원가입 시 is_active=False로 설정되는 문제 발생
serializer에서 exclude로 제외하는 것으로 해결
> :bug:Fix: 회원가입시 오류 수정 #3

- users/serializers.py
> :sparkles:Feat: payload nickname 추가

- exhibitions/views.py
검색대상 전시회로 한정
검색 필드에 장소 추가
Q를 통해 or 조건 설정
```python
if search:
exhibitions = Exhibition.objects.filter(
Q(content__icontains=search)
| Q(info_name__icontains=search)
| Q(location__icontains=search)
).order_by("-created_at")
```
> :hammer:Refact: 검색 대상 변경 #28

- accompanies/serializers.py
- accompanies/views.py
[views.py]
동행 신청하기 시리얼라이저 통합으로 인해 시리얼라이저 실행하는 부분
수정했습니다.
[serializers.py]
1. ApplyCreateSerializer 삭제하고, ApplySerializer 하나만 쓸 수 있게 수정하였습니다.
2. AccompanySerializer는 통합 불가능하여 두 시리얼라이저 그대로 두었습니다.
3. 동행 신청글 작성 시 필요한 데이터를 반환하게끔 수정하였습니다.
> :sparkles:Feat: 시리얼라이저 관련 수정 #23 #24 #29 #30

- users/serializers.py
> :hammer:Refact: payload 로그인 타입 추가 #3

- accompanies/views.py
리뷰 함수와 똑같이 raise_exception=True 옵션을 추가하고 용법에 맞게 수정했습니다.
글 수정 및 삭제 시 글 작성자와 일치하지 않아서 "권한이 없습니다."
메시지를 띄우는 부분에 serializer.error를 추가했던 오류가 있어
삭제했습니다.
> :bug:Fix: 동행글 작성/수정 함수에 is_valid 용법에 맞게 수정 #23 #24 #29 #30

- users/views.py
user.is_active 값을 확인하여 탈퇴한 유저인지 체크 추가
> :bug:Fix: 소셜 로그인 에러 수정 #5 #7

- exhibitions/serializers.py
지도 API를 활용하기 위해
longitude, latitude 필드 추가했습니다
> 🔨Refact: 위도,경도 추가

- b4_drf_project/settings.py
악의적으로 API로 접근해 보안 취약점을 파악하는
경우를 막기 위한 수정 사항 반영
> :hammer:Refact: API 접근 수정 #142

- b4_drf_project/settings.py
튜플 형태로 선언하지 않아서 설정을 인식하지 못하던 오류 수정
> :bug:Fix: REST_FRAMEWORK 설정 오류 수정 #142
